# Generated by Django 5.1.2 on 2024-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="personnel_images", verbose_name="عکس پرسنل"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[("TEACHER", "استاد"), ("STAFF", "کارمند")],
                        max_length=100,
                        verbose_name="نوع پرسنل",
                    ),
                ),
                ("job", models.CharField(max_length=200, verbose_name="شغل")),
                ("is_active", models.BooleanField(verbose_name="فعال / غیر فعال")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="تاریخ اخرین بروز رسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسنل",
                "verbose_name_plural": "لیست پرسنل",
            },
        ),
    ]
