# Generated by Django 5.1.2 on 2024-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="شرح موقعیت شغلی")),
                ("gender", models.CharField(max_length=5, verbose_name="جنسیت")),
                ("age", models.CharField(max_length=250, verbose_name="سن")),
                (
                    "literacy_level",
                    models.CharField(max_length=200, verbose_name="سطح سواد"),
                ),
                (
                    "minimum_work_experience",
                    models.CharField(
                        max_length=200, verbose_name="حداقل سابقه کاری مورد نیاز"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="فعال / غیر فعال")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="تاریخ اخرین بروز رسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "فرصت شغلی",
                "verbose_name_plural": "فرصت های شغلی",
            },
        ),
    ]
