# Generated by Django 5.1.2 on 2024-11-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_opportunity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopportunity",
            name="place",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="مکان"
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="عنوان"
            ),
        ),
    ]
