# Generated by Django 5.1.2 on 2024-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestingCooperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="پست الکترونیکی"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تماس"),
                ),
                ("gender", models.CharField(max_length=5, verbose_name="جنسیت")),
                (
                    "date_of_birth",
                    models.CharField(max_length=200, verbose_name="تاریخ تولد"),
                ),
                (
                    "marital_status",
                    models.CharField(max_length=100, verbose_name="وضعیت تاهل"),
                ),
                (
                    "military_status",
                    models.CharField(max_length=150, verbose_name="وضعیت نظام وظیفه"),
                ),
                (
                    "type_of_cooperation",
                    models.CharField(max_length=150, verbose_name="نوع همکاری"),
                ),
                (
                    "rights_requested",
                    models.PositiveBigIntegerField(verbose_name="حقوق درخواستی"),
                ),
                ("description", models.TextField(verbose_name="توضیحات درباره همکاری")),
                (
                    "resume",
                    models.FileField(upload_to="resumes", verbose_name="فایل رزومه"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="collaboration_avatars", verbose_name="تصویر پروفایل"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="تاریخ اخرین بروز رسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست های همکاری",
            },
        ),
    ]
