# Generated by Django 5.1.2 on 2024-11-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooperation", "0001_initial"),
        ("job_opportunity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestingcooperation",
            name="job_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="job_opportunity.jobopportunity",
                verbose_name="فرصت شغلی",
            ),
        ),
    ]
