# Generated by Django 5.1.2 on 2024-10-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره همراه"
            ),
        ),
    ]
